# Generated by Django 5.1.4 on 2025-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_groups_group_category_groups_group_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_image',
            field=models.ImageField(null=True, upload_to='static/group_dp/'),
        ),
    ]
