# Generated by Django 5.1.4 on 2025-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_groups_group_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('groupname', models.CharField(max_length=100)),
            ],
        ),
    ]
