# Generated by Django 5.1.4 on 2025-02-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_messages_attachfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='unsent',
            field=models.BooleanField(null=True),
        ),
    ]
