# Generated by Django 5.1.4 on 2025-02-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_date_user_email_user_password_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intrest',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
