# Generated by Django 5.1.4 on 2025-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_intrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
