# Generated by Django 5.1.4 on 2025-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='user_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
