# Generated by Django 5.1.4 on 2025-02-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_groups_user_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('time_spent', models.CharField(max_length=500)),
            ],
        ),
    ]
