# Generated by Django 5.1.4 on 2025-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_timespent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSpent',
        ),
        migrations.AddField(
            model_name='user',
            name='time_spent',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
