# Generated by Django 5.1.4 on 2025-02-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_intrestnotifition'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='creator',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
