# Generated by Django 5.1.4 on 2025-02-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_groups_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_data',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
