# Generated by Django 5.1.4 on 2025-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_points_user_rank_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='weekly_data',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
