# Generated by Django 5.1.4 on 2025-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_groups_weekly_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank_data',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
